language: python

python:
    - "2.7"

install:
    - pip install coveralls
    - pip install -r requirements.txt
    - make install

script:
    coverage run -m unittest discover

after_success:
coveralls
